"""add usuario_plan

Revision ID: 08f54ab0414a
Revises: e8f57490c916
Create Date: 2026-08-03 18:55:04.968208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f54ab0414a'
down_revision: Union[str, Sequence[str], None] = 'e8f57490c916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_plan',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plan_estudios_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_estudios_id'], ['plan_estudios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'plan_estudios_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_plan')
    # ### end Alembic commands ###
