"""initial schema

Revision ID: 23b76a65ce34
Revises: 
Create Date: 2026-08-03 17:42:33.934151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23b76a65ce34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('tipologia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignatura_codigo'), 'asignatura', ['codigo'], unique=True)
    op.create_table('facultad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facultad_codigo'), 'facultad', ['codigo'], unique=True)
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('profesor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jornada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cupos_disponibles', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_asignatura_id'), 'grupo', ['asignatura_id'], unique=False)
    op.create_table('plan_estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_estudios_codigo'), 'plan_estudios', ['codigo'], unique=True)
    op.create_table('asignatura_plan',
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('plan_estudios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['plan_estudios_id'], ['plan_estudios.id'], ),
    sa.PrimaryKeyConstraint('asignatura_id', 'plan_estudios_id')
    )
    op.create_table('grupo_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('dia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_horario_grupo_id'), 'grupo_horario', ['grupo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grupo_horario_grupo_id'), table_name='grupo_horario')
    op.drop_table('grupo_horario')
    op.drop_table('asignatura_plan')
    op.drop_index(op.f('ix_plan_estudios_codigo'), table_name='plan_estudios')
    op.drop_table('plan_estudios')
    op.drop_index(op.f('ix_grupo_asignatura_id'), table_name='grupo')
    op.drop_table('grupo')
    op.drop_index(op.f('ix_facultad_codigo'), table_name='facultad')
    op.drop_table('facultad')
    op.drop_index(op.f('ix_asignatura_codigo'), table_name='asignatura')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
