"""add historia_academica

Revision ID: 79bcdf51ba76
Revises: 08f54ab0414a
Create Date: 2026-08-03 20:09:22.832616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '79bcdf51ba76'
down_revision: Union[str, Sequence[str], None] = '08f54ab0414a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_academica',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plan_codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('facultad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('porcentaje_avance', sa.Float(), nullable=True),
    sa.Column('promedio_acumulado', sa.Float(), nullable=True),
    sa.Column('papa_acumulado', sa.Float(), nullable=True),
    sa.Column('asignaturas', sa.JSON(), nullable=True),
    sa.Column('resumen_creditos', sa.JSON(), nullable=True),
    sa.Column('actualizado_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historia_academica')
    # ### end Alembic commands ###
