"""scope asignatura by sede and plan by facultad

Revision ID: 9387ad175a04
Revises: bf13eb0771d1
Create Date: 2026-08-04 07:33:00.893760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9387ad175a04'
down_revision: Union[str, Sequence[str], None] = 'bf13eb0771d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added nullable first: every asignatura row scraped so far came from
    # a Medellin-scoped crawl (or a since-corrected cross-sede mixup --
    # see the crawl.py fix in the same change), so backfill before making
    # the column required.
    op.add_column('asignatura', sa.Column('sede', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE asignatura SET sede = 'medellin' WHERE sede IS NULL")
    op.alter_column('asignatura', 'sede', nullable=False)
    op.drop_index(op.f('ix_asignatura_codigo'), table_name='asignatura')
    op.create_index(op.f('ix_asignatura_codigo'), 'asignatura', ['codigo'], unique=False)
    op.create_index(op.f('ix_asignatura_sede'), 'asignatura', ['sede'], unique=False)
    op.create_unique_constraint('uq_asignatura_codigo_sede', 'asignatura', ['codigo', 'sede'])
    op.drop_index(op.f('ix_plan_estudios_codigo'), table_name='plan_estudios')
    op.create_index(op.f('ix_plan_estudios_codigo'), 'plan_estudios', ['codigo'], unique=False)
    op.create_unique_constraint('uq_plan_codigo_facultad', 'plan_estudios', ['codigo', 'facultad_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plan_codigo_facultad', 'plan_estudios', type_='unique')
    op.drop_index(op.f('ix_plan_estudios_codigo'), table_name='plan_estudios')
    op.create_index(op.f('ix_plan_estudios_codigo'), 'plan_estudios', ['codigo'], unique=True)
    op.drop_constraint('uq_asignatura_codigo_sede', 'asignatura', type_='unique')
    op.drop_index(op.f('ix_asignatura_sede'), table_name='asignatura')
    op.drop_index(op.f('ix_asignatura_codigo'), table_name='asignatura')
    op.create_index(op.f('ix_asignatura_codigo'), 'asignatura', ['codigo'], unique=True)
    op.drop_column('asignatura', 'sede')
    # ### end Alembic commands ###
