"""add sede to facultad

Revision ID: bf13eb0771d1
Revises: 3a1bc1f0c7af
Create Date: 2026-08-04 06:05:32.239430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf13eb0771d1'
down_revision: Union[str, Sequence[str], None] = '3a1bc1f0c7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added nullable first: every facultad row scraped so far is from the
    # Medellin-only crawl, so backfill before making the column required.
    op.add_column('facultad', sa.Column('sede', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE facultad SET sede = 'medellin' WHERE sede IS NULL")
    op.alter_column('facultad', 'sede', nullable=False)
    op.drop_index(op.f('ix_facultad_codigo'), table_name='facultad')
    op.create_index(op.f('ix_facultad_codigo'), 'facultad', ['codigo'], unique=False)
    op.create_index(op.f('ix_facultad_sede'), 'facultad', ['sede'], unique=False)
    op.create_unique_constraint('uq_facultad_codigo_sede', 'facultad', ['codigo', 'sede'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_facultad_codigo_sede', 'facultad', type_='unique')
    op.drop_index(op.f('ix_facultad_sede'), table_name='facultad')
    op.drop_index(op.f('ix_facultad_codigo'), table_name='facultad')
    op.create_index(op.f('ix_facultad_codigo'), 'facultad', ['codigo'], unique=True)
    op.drop_column('facultad', 'sede')
    # ### end Alembic commands ###
