"""add aula to grupo_horario

Revision ID: e43e6951d648
Revises: 9387ad175a04
Create Date: 2026-08-04 08:48:03.735956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e43e6951d648'
down_revision: Union[str, Sequence[str], None] = '9387ad175a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupo_horario', sa.Column('aula', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grupo_horario', 'aula')
    # ### end Alembic commands ###
